ln -s ~/dotfiles/vim/vimrc ~/.vimrc
ln -s ~/dotfiles/zshrc ~/.zshrc
ln -s ~/dotfiles/ssh ~/.ssh
ln -s ~/dotfiles/oh-my-zsh ~/.oh-my-zsh
ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/tern-config ~/.tern-config
ln -s ~/dotfiles/editorconfig ~/.editorconfig
ln -s ~/dotfiles/vscode ~/.vscode
ln -s ~/dotfiles/lint/eslintrc.yml ~/.eslintrc.yml
ln -s ~/dotfiles/.jupyter ~/.jupyter
